config/routes.rb
Rails.application.routes.draw do
  
  root to: 'users#index'

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    resources :relationships, only: [:create, :destroy]

    member do
      get :following, :followers
    end
  end

  get 'users/:id', to: 'users#show'
  get 'who_to_follow', to: 'users#who_to_follow'

  resources :posts do
    resources :comments
  end
  
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts, only: [:index, :show, :update, :destroy]
      resources :users, only: [:show, :create, :update, :destroy]
      post 'login', to: 'sessions#create', as: :login
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, 
          :registerable,
          :recoverable,
          :rememberable,
          :trackable,
          :validatable
  
  validates :email, uniqueness: { case_sensitive: false, message: 'email already registered' }
  validates :first_name, length: { in: 2..12, too_short: 'too short first name', too_long: 'too long first name' }
  validates :last_name, length: { in: 2..12, too_short: 'too short last name', too_long: 'too long last name' }
  validates :nickname, uniqueness: { case_sensitive: false, message: '@nickname must be  uniq' }, 
            length: { in: 2..12, too_short: 'too short nickname', too_long: 'too long nickname' }

  before_validation do |user|
    user.authentication_token = generate_authentication_token
    user.nickname = generate_nickname(user)    
  end

  mount_uploader :avatar, AvatarUploader
  validate :avatar_image_size

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Too complex
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  # Too complex
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    @post = Post.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id)
    @post.reverse.each
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
  
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  private

    def avatar_image_size
      if avatar.size > 5.megabytes
        errors.add(:avatar, "should be less than 5MB")
      end
    end

    def generate_authentication_token
      loop do
        token = SecureRandom.hex
        break token unless self.class.exists?(authentication_token: token)
      end
    end
    
    def generate_nickname(user)
      nickname = "#{ user.first_name }_#{ user.last_name }"[0..11]
      i = 100
      loop do
        break nickname unless self.class.exists?(nickname: nickname)
        nickname = "#{user.first_name}"[0..8]
        nickname = nickname + i.to_s
        i+=1
      end
    end
end

app/controllers/api/v1/users_controller.rb
class API::V1::UsersController < API::V1::ApplicationController

  before_action :set_user, only: [:show, :update, :destroy]

  def index
  end
  
  def show
    render json: @user, status: 200
  end

  def update
    if @user.update_attributes(user_params)
      render json: @user, status: 202
    else
      render json: @user, status: 400
    end
  end

  def destroy
    unless @user.nil?
      @user.destroy
      render nothing: true, status: 410
    else
      render nothing: true, status: 404
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :nickname)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_who_to_follow, only: [:index, :show, :followers, :following, :who_to_follow]
  expose_decorated :user
  expose_decorated :post
  
  def update
    if user.update(user_params)
      redirect_to user
    else
      render :edit, alert: "Could not update, Please try again"
    end
  end

  private
  
    def set_who_to_follow
      @who_to_follow = User.where.not(id: current_user.following.map(&:id) << current_user.id)
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :nickname, :avatar)
    end
end

app/views/users/_follow.html.slim
= link_to 'follow', user_relationships_path(user), remote: true, method: :post

app/views/users/_followers.html.slim
.row
  .large-12.colomns.centered
    br
    | followers
    br
    - user.followers.each do |follower|
      = link_to user.get_nickname(follower), "/users/#{follower.id}"
      br

app/views/users/_following.html.slim
.row
  .large-12.colomns.centered
    br
    | following
    br
    - user.following.each do |following|
      = link_to user.get_nickname(following), "/users/#{following.id}"
      br

app/views/users/_unfollow.html.slim
= link_to 'unfollow', "/users/#{ user.id }/relationships/#{ user.id }", remote: true, method: :delete

app/views/users/_user_header.html.slim
.top-line
.row.large-collapse.full-width.header
  .large-4.small-4.colomns
  .large-8.small-8.columns
    = link_to user_path, class: "hollow button small-2 columns static" do
      |post
      .div
        = user.posts.count
    end

    = link_to following_user_path, class: "hollow button small-2 columns" do
      |following
      .div
        = user.following.count
    end

    = link_to followers_user_path, class: "hollow button small-2 columns" do
      |followers
      .div
        = user.followers.count
    end


.profile-info
  div
    img src="/assets/Profile-Avatar.jpg" alt="альтернативный текст" class="avatar"
  
  .user-info
    div class="follow"
      - if !current_user.nil? && current_user != user
        - if current_user.following?(user)
          = link_to 'unfollow', user_relationship_path(user), remote: true, method: :delete
        - else
          = link_to 'follow', user_relationships_path(user), remote: true, method: :post
      - else 
        = link_to 'edit', edit_user_registration_path
    .full-name
      = user.full_name
    div
      = link_to user.at_nickname, user_path, class: "at_nickname"
    div
      | Joined 
      = user.joined_at

app/views/users/_user_page.html.slim
.top-line
.row.full-width.user-statistic
  .small-4.medium-4.large-4.columns
  .small-8.medium-8.large-8.columns
    = link_to user_path, class: "hollow button" do
      |post
      .post-count
        = user.posts.count
    end
    = link_to following_user_path, class: "hollow button" do
      |following
      .div
        span#following-count
          = user.following.count
    end
    = link_to followers_user_path, class: "hollow button" do
      |followers
      .div
        span#followers-count
          = user.followers.count
    end
.row.full-width.profile-info
  .small-4.medium-4.large-4.columns.page-avatar-container
    .small-12.medium-12.large-12.columns.page-avatar-container
      - if user.avatar?
        = image_tag(user.avatar_url(:thumb), class: 'page-avatar', alt: 'avatar')
      - else
        = image_tag('default-avatar.jpg', class: 'page-avatar', alt: 'avatar')
      .user-info
        .follow
          - if !current_user.nil? && current_user != user
            - if current_user.following?(user)
              = render 'unfollow'
            - else
              = render 'follow'
          - else
            = link_to 'edit', edit_user_path

        .full-name
          = user.full_name
        div
          = link_to user.at_nickname, user_path, class: "at_nickname"
        div
          | Joined
          = user.joined_at
  .small-6.medium-6.large-6.columns
    - if current_page?(user_path)
      = render 'feed'
    - elsif current_page?(following_user_path)
      = render 'following'
    - elsif current_page?(followers_user_path)
      = render 'followers'

  .small-2.medium-2.large-2.columns

app/views/users/_who_can_follow.html.slim
.who-can-follow-container.white-background
  |who can follow 
  = link_to 'view all', users_path
  br
  - @who_can_follow.each do |can_follow|
    = link_to user.get_nickname(can_follow), can_follow
    br

app/views/users/_who_to_follow.html.slim
.who-to-follow-container.white-background
  |who to follow 
  = link_to 'view all', who_to_follow_path
  br
  - @who_to_follow.each do |can_follow|
    = link_to user.get_nickname(can_follow), can_follow
    br

app/views/users/edit.html.slim
= simple_form_for user, html: { multipart: true } do |f|
  div.form-inputs
    = f.input :first_name
    = f.input :last_name
    = f.input :nickname
    label My Avatar
    = image_tag(user.avatar_url) if user.avatar?
    = f.file_field :avatar
    = f.hidden_field :avatar_cache
    = f.button :submit, 'Update'
= link_to "Back", :back

app/views/users/followers.html.slim
= render 'user_page'

app/views/users/following.html.slim
= render 'user_page'

app/views/users/index.html.slim
.index-page
  - if user_signed_in?
    .row.full-width
      .small-4.medium-4.large-4.columns
        .row.index-background-line
        .row.index-profile.white-background
          .small-6.medium-6.large-5.columns.avatar-container
            - if current_user.avatar?
              = image_tag(current_user.avatar_url(:thumb), class: 'index-avatar', alt: 'avatar')
            - else
              = image_tag('default-avatar.jpg', class: 'index-avatar', alt: 'avatar')
          .small-6.medium-6.large-7.columns.reset-padding
            = current_user.full_name
            br
            = link_to current_user.at_nickname, "/users/#{current_user.id}", class: "at_nickname"  
        .row.index-profile-statistic.white-background
          .small-4.medium-4.large-4.columns.statistic-btn-container
            = link_to "/users/#{ current_user.id }", class: 'statistic-btn' do
              |post
              .post-count
                = current_user.posts.count
            end
          .small-4.medium-4.large-4.columns.white-background.statistic-btn-container
            = link_to "/users/#{ current_user.id }/following", class: 'statistic-btn' do
              |following
              .div
                = current_user.following.count
            end
          .small-4.medium-4.large-4.columns.white-background.statistic-btn-container
            = link_to "/users/#{ current_user.id }/followers", class: 'statistic-btn' do
              |followers
              .div
                = current_user.followers.count
            end
        .row.row-distance
          .small-12.medium-12.show-for-medium-only
            = render 'users/who_to_follow'
          .small-12.medium-12.show-for-small-only
            = render 'users/who_to_follow'
      .small-8.medium-8.large-8.columns
        .small-12.medium-12.large-8.columns
          .row.full-width.small-12.medium-12.large-12.columns
            = render 'posts/form'
          = render 'users/feed'
        .large-4.columns.show-for-large.reset-padding
          = render 'users/who_to_follow'
  - else
    = link_to 'sign in', new_user_session_path

app/views/users/show.html.slim
= render 'user_page'

app/views/users/who_to_follow.html.slim
- if user_signed_in?
  br
  br
  - @who_to_follow.each do |user|
    = link_to user.email, user
    br
- else
 - redirect_to root_path